# Generated by Django 5.0.7 on 2024-08-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='photos/imagecrop')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
