# Generated by Django 3.1 on 2024-08-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20240801_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
