# Generated by Django 5.0.7 on 2024-08-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_product_color_product_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='lens_color',
        ),
        migrations.AddField(
            model_name='product',
            name='frame_model',
            field=models.CharField(default='aviator', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(default='unisex', max_length=20),
        ),
    ]
