# Generated by Django 5.0.7 on 2024-08-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_rename_color_product_lens_color_product_frame_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.CharField(choices=[('polarized', 'Polarized'), ('gradient', 'Gradient'), ('sales', 'Sales'), ('discount', 'Discount'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
