# Generated by Django 5.0.7 on 2024-08-12 12:10

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_product_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photos/products'),
        ),
    ]
