# Generated by Django 5.0.7 on 2024-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_product_image2_alter_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.CharField(choices=[('polarized', 'Polarized'), ('gradient', 'Gradient'), ('uv protection', 'UV Protection'), ('color changing', 'Color Changing'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
