# Generated by Django 5.0.7 on 2024-08-24 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_alter_productoffer_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productoffer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_products', to='Store.productoffer'),
        ),
    ]
