# Generated by Django 5.0.7 on 2024-08-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_remove_wishlist_product_wishlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productoffer',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
