# Generated by Django 5.0.7 on 2024-08-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_remove_productoffer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
