# Generated by Django 5.0.7 on 2024-08-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_amount',
        ),
    ]
