# Generated by Django 5.0.7 on 2024-08-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0024_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_amount',
            new_name='offer_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
    ]
