# Generated by Django 5.0.7 on 2024-09-01 11:15

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0028_rename_images_imagegallery_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='images',
            field=imagekit.models.fields.ProcessedImageField(default='Null', upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_images', to='Store.variation'),
        ),
    ]
