# Generated by Django 5.0.7 on 2024-09-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0032_alter_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
