# Generated by Django 5.0.7 on 2024-09-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0033_variation_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
