# Generated by Django 5.0.7 on 2024-09-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0034_variation_offer_price_variation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
