# Generated by Django 5.0.7 on 2024-09-08 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0036_alter_imagegallery_images_alter_variation_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='variation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Store.variation'),
        ),
    ]
