# Generated by Django 5.0.7 on 2024-09-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0038_alter_imagegallery_images_alter_variation_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='variation',
            field=models.ManyToManyField(to='Store.variation'),
        ),
    ]
