# Generated by Django 5.0.7 on 2024-09-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0028_rename_images_imagegallery_variation'),
        ('carts', '0006_cart_discount_cart_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='Store.variation'),
        ),
    ]
