# Generated by Django 5.0.7 on 2024-09-06 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0033_variation_stock'),
        ('carts', '0008_coupon_minimum_amount_coupon_usage_limit_usercoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
        migrations.CreateModel(
            name='CartItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cartitem')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.variation')),
            ],
        ),
    ]
