# Generated by Django 5.0.7 on 2024-09-09 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0038_alter_imagegallery_images_alter_variation_images'),
        ('carts', '0009_remove_cartitem_quantity_remove_cartitem_variations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.variation'),
        ),
        migrations.DeleteModel(
            name='CartItemVariation',
        ),
    ]
