# Generated by Django 5.0.7 on 2024-09-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0038_alter_imagegallery_images_alter_variation_images'),
        ('carts', '0010_cartitem_quantity_cartitem_variation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'cart', 'variation')},
        ),
    ]
