# Generated by Django 3.1 on 2024-08-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20240801_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='7c2bca', max_length=6),
        ),
    ]
