# Generated by Django 3.1 on 2024-08-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20240801_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='cee2df', max_length=6),
        ),
    ]
