# Generated by Django 3.1 on 2024-08-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20240801_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a983f1', max_length=6),
        ),
    ]
