# Generated by Django 3.1 on 2024-08-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20240801_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='aa7cdb', max_length=6),
        ),
    ]
