# Generated by Django 3.1 on 2024-08-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20240801_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='db2baf', max_length=6),
        ),
    ]
