# Generated by Django 3.1 on 2024-08-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_auto_20240802_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='fccd00', max_length=6),
        ),
    ]
