# Generated by Django 5.0.7 on 2024-08-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_alter_account_id_alter_otptoken_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='fb759c', max_length=6),
        ),
    ]
