# Generated by Django 5.0.7 on 2024-08-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0038_alter_otptoken_otp_code_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='67bc17', max_length=6),
        ),
    ]
