# Generated by Django 5.0.7 on 2024-08-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0054_alter_address_country_alter_address_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='644cea', max_length=6),
        ),
    ]
