# Generated by Django 5.0.7 on 2024-08-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0087_alter_otptoken_otp_code_wallet_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0ab35a', max_length=6),
        ),
    ]
