# Generated by Django 5.0.7 on 2024-09-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0166_alter_otptoken_otp_code_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='fefda7', max_length=6),
        ),
    ]
