# Generated by Django 5.0.7 on 2024-09-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0196_alter_otptoken_otp_code_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5eebc9', max_length=6),
        ),
    ]
