# Generated by Django 5.0.7 on 2024-08-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_category_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
