# Generated by Django 5.0.7 on 2024-08-12 11:14

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('brand_logo', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
