# Generated by Django 5.0.7 on 2024-08-12 11:57

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0005_alter_category_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='category',
            name='brand_logo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photos/categories'),
        ),
    ]
