# Generated by Django 5.0.7 on 2024-08-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
