# Generated by Django 5.0.7 on 2024-08-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_order_shipping_cost_order_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
