# Generated by Django 5.0.7 on 2024-08-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_order_final_amount'),
        ('carts', '0005_remove_cart_coupon_cart_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='carts.coupon'),
        ),
    ]
