# Generated by Django 5.0.7 on 2024-08-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orderproduct'),
        ),
    ]
