# Generated by Django 5.0.7 on 2024-08-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0012_alter_return_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='product',
        ),
    ]
