# Generated by Django 5.0.7 on 2024-09-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0014_orderproduct_variation_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sub_total',
        ),
    ]
