# Generated by Django 5.0.7 on 2024-09-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0018_transaction_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
