# Generated by Django 5.0.7 on 2024-09-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0019_remove_transaction_order_transaction_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_number',
            field=models.CharField(default=234, max_length=20),
        ),
    ]
